export const tokens = {
  themes: {
    default: {
      theme: {
        colors: {
          'secondary-text': '#fff',
          'secondary-100': '#fee9ea',
          'secondary-200': '#fedfdf',
          'secondary-300': '#fdbfbf',
          'secondary-400': '#e1020f',
          'secondary-500': '#c91a1f',
          'secondary-600': '#5e2b2b',
          'secondary-700': '#3b2424',
          'secondary-800': '#341f1f',
          'secondary-900': '#2b1919',
          'info-text': '#0078f3',
          'info-100': '#E8EDFF',
          'info-200': '#DDE5FF',
          'info-300': '#BCCDFF',
          'info-400': '#518FFF',
          'info-500': '#0078F3',
          'info-600': '#0063CB',
          'info-700': '#273961',
          'info-800': '#222A3F',
          'info-900': '#1D2437',
          'greyscale-100': '#eee',
          'greyscale-200': '#E5E5E5',
          'greyscale-300': '#CECECE',
          'greyscale-400': '#929292',
          'greyscale-500': '#7C7C7C',
          'greyscale-600': '#666666',
          'greyscale-700': '#3A3A3A',
          'greyscale-800': '#2A2A2A',
          'greyscale-900': '#242424',
          'greyscale-000': '#fff',
          'primary-100': '#ECECFE',
          'primary-200': '#E3E3FD',
          'primary-300': '#CACAFB',
          'primary-400': '#8585F6',
          'primary-500': '#6A6AF4',
          'primary-600': '#313178',
          'primary-700': '#272747',
          'primary-800': '#000091',
          'primary-900': '#21213F',
          'success-100': '#dffee6',
          'success-200': '#b8fec9',
          'success-300': '#88fdaa',
          'success-400': '#3bea7e',
          'success-500': '#1f8d49',
          'success-600': '#18753c',
          'success-700': '#204129',
          'success-800': '#1e2e22',
          'success-900': '#19281d',
          'warning-100': '#fff4f3',
          'warning-200': '#ffe9e6',
          'warning-300': '#ffded9',
          'warning-400': '#ffbeb4',
          'warning-500': '#d64d00',
          'warning-600': '#b34000',
          'warning-700': '#5e2c21',
          'warning-800': '#3e241e',
          'warning-900': '#361e19',
          'danger-100': '#FFE9E9',
          'danger-200': '#FFDDDD',
          'danger-300': '#FFBDBD',
          'danger-400': '#FF5655',
          'danger-500': '#F60700',
          'danger-600': '#CE0500',
          'danger-700': '#642626',
          'danger-800': '#412121',
          'danger-900': '#391C1C',
          'primary-text': '#000091',
          'success-text': '#1f8d49',
          'warning-text': '#d64d00',
          'danger-text': '#FFF',
          'primary-050': '#F5F5FE',
          'primary-150': '#F4F4FD',
          'greyscale-text': '#303C4B',
          'greyscale-050': '#F6F6F6',
          'greyscale-250': '#ddd',
          'greyscale-350': '#ddd',
          'greyscale-750': '#353535',
          'greyscale-950': '#1E1E1E',
          'greyscale-1000': '#161616',
          'primary-action': '#1212FF',
          'primary-bg': '#FAFAFA',
          'blue-400': '#7AB1E8',
          'blue-500': '#417DC4',
          'blue-600': '#3558A2',
          'brown-400': '#E6BE92',
          'brown-500': '#BD987A',
          'brown-600': '#745B47',
          'cyan-400': '#34BAB5',
          'cyan-500': '#009099',
          'cyan-600': '#006A6F',
          'gold-400': '#FFCA00',
          'gold-500': '#C3992A',
          'gold-600': '#695240',
          'green-400': '#34CB6A',
          'green-500': '#00A95F',
          'green-600': '#297254',
          'olive-400': '#99C221',
          'olive-500': '#68A532',
          'olive-600': '#447049',
          'orange-400': '#FF732C',
          'orange-500': '#E4794A',
          'orange-600': '#755348',
          'pink-400': '#FFB7AE',
          'pink-500': '#E18B76',
          'pink-600': '#8D533E',
          'purple-400': '#CE70CC',
          'purple-500': '#A558A0',
          'purple-600': '#6E445A',
          'yellow-400': '#D8C634',
          'yellow-500': '#B7A73F',
          'yellow-600': '#66673D',
        },
        font: {
          sizes: {
            h1: '2rem',
            h2: '1.75rem',
            h3: '1.5rem',
            h4: '1.375rem',
            h5: '1.25rem',
            h6: '1.125rem',
            l: '1rem',
            m: '0.8125rem',
            s: '0.75rem',
            xs: '0.75rem',
            sm: '0.875rem',
            md: '1rem',
            lg: '1.125rem',
            ml: '0.938rem',
            xl: '1.25rem',
            t: '0.6875rem',
            'xl-alt': '5rem',
            'lg-alt': '4.5rem',
            'md-alt': '4rem',
            'sm-alt': '3.5rem',
            'xs-alt': '3rem',
          },
          weights: {
            thin: 100,
            light: 300,
            regular: 400,
            medium: 500,
            bold: 600,
            extrabold: 800,
            black: 900,
          },
          families: { base: 'Marianne', accent: 'Marianne' },
          letterSpacings: {
            h1: 'normal',
            h2: 'normal',
            h3: 'normal',
            h4: 'normal',
            h5: '1px',
            h6: 'normal',
            l: 'normal',
            m: 'normal',
            s: 'normal',
          },
        },
        spacings: {
          '0': '0',
          xl: '2.5rem',
          l: '3rem',
          b: '1.625rem',
          s: '1rem',
          t: '0.5rem',
          st: '0.25rem',
          none: '0',
          auto: 'auto',
          bx: '2.2rem',
          full: '100%',
          '4xs': '0.125rem',
          '3xs': '0.25rem',
          '2xs': '0.375rem',
          xs: '0.5rem',
          sm: '0.75rem',
          base: '1rem',
          md: '1.5rem',
          lg: '2rem',
          xxl: '3rem',
          xxxl: '3.5rem',
          '4xl': '4rem',
          '5xl': '4.5rem',
          '6xl': '6rem',
          '7xl': '7.5rem',
        },
        transitions: {
          'ease-in': 'cubic-bezier(0.32, 0, 0.67, 0)',
          'ease-out': 'cubic-bezier(0.33, 1, 0.68, 1)',
          'ease-in-out': 'cubic-bezier(0.65, 0, 0.35, 1)',
          duration: '250ms',
        },
        breakpoints: {
          xs: '480px',
          sm: '576px',
          md: '768px',
          lg: '992px',
          xl: '1200px',
          xxl: '1400px',
          xxs: '320px',
          mobile: '768px',
          tablet: '1024px',
        },
        logo: {
          src: '/assets/logo-gouv.svg',
          widthHeader: '110px',
          widthFooter: '220px',
          alt: 'Gouvernement Logo',
        },
      },
      components: {
        modal: { 'width-small': '342px' },
        button: {
          'medium-height': '40px',
          'medium-text-height': '40px',
          'border-radius': '4px',
          'small-height': '26px',
          primary: {
            'background--color': 'var(--c--theme--colors--primary-text)',
            'background--color-hover': '#1212ff',
            'background--color-active': '#2323ff',
            'background--color-disabled':
              'var(--c--theme--colors--greyscale-100)',
            color: '#fff',
            'color-hover': '#fff',
            'color-active': '#fff',
            'color-focus-visible': '#fff',
            disabled: 'var(--c--theme--colors--greyscale-500)',
          },
          'primary-text': {
            'background--color': 'var(--c--theme--colors--primary-text)',
            'background--color-hover': 'var(--c--theme--colors--greyscale-100)',
            'background--color-active': 'var(--c--theme--colors--primary-100)',
            'background--color-focus-visible': '#fff',
            'background--color-disabled':
              'var(--c--theme--colors--greyscale-000)',
            color: 'var(--c--theme--colors--primary-800)',
            'color-hover': 'var(--c--theme--colors--primary-800)',
            disabled: 'var(--c--theme--colors--greyscale-400)',
          },
          secondary: {
            'background--color-hover': '#F6F6F6',
            'background--color-active': '#EDEDED',
            'background--color-focus-visible':
              'var(--c--theme--colors--greyscale-000)',
            'background--disabled': 'var(--c--theme--colors--greyscale-000)',
            color: 'var(--c--theme--colors--primary-800)',
            'border--color': 'var(--c--theme--colors--greyscale-300)',
            'border--color-hover': 'var(--c--theme--colors--greyscale-300)',
            'border--color-disabled': 'var(--c--theme--colors--greyscale-300)',
            disabled: 'var(--c--theme--colors--greyscale-400)',
          },
          tertiary: {
            'background--color': 'var(--c--theme--colors--primary-100)',
            'background--color-focus-visible':
              'var(--c--theme--colors--primary-100)',
            'background--color-hover': 'var(--c--theme--colors--primary-300)',
            'background--color-active': 'var(--c--theme--colors--primary-300)',
            'background--disabled': 'var(--c--theme--colors--primary-050)',
            color: 'var(--c--theme--colors--primary-800)',
            disabled: 'var(--c--theme--colors--primary-300)',
          },
          'tertiary-text': {
            'background--color-hover': 'var(--c--theme--colors--greyscale-100)',
            'color-hover': 'var(--c--theme--colors--primary-text)',
            color: 'var(--c--theme--colors--primary-600)',
          },
          danger: {
            'color-hover': 'white',
            'background--color': 'var(--c--theme--colors--danger-600)',
            'background--color-hover': '#FF2725',
            'background--color-focus-visible':
              'var(--c--theme--colors--danger-600)',
            'background--color-disabled':
              'var(--c--theme--colors--greyscale-100)',
            'color-disabled': 'var(--c--theme--colors--greyscale-400)',
          },
        },
        datagrid: {
          'header--color': '#666666',
          'header--size': '12px',
          'header--weight': '500',
          'body--background-color-hover': '#eee',
        },
        'forms-checkbox': {
          'border-radius': '4px',
          'border-color': 'var(--c--theme--colors--primary-800)',
          'background-color--hover': 'var(--c--theme--colors--greyscale-100)',
          'border--color-disabled': 'var(--c--theme--colors--greyscale-200)',
          'border--color': 'var(--c--theme--colors--primary-800)',
          'background--disabled': 'var(--c--theme--colors--greyscale-200)',
          'background--enable': 'var(--c--theme--colors--primary-800)',
          'check--disabled': 'var(--c--theme--colors--greyscale-300)',
          'check--enable': 'var(--c--theme--colors--greyscale-000)',
          color: 'var(--c--theme--colors--primary-text)',
          'label--color': 'var(--c--theme--colors--greyscale-1000)',
          'label--size': 'var(--c--theme--font--sizes--sm)',
          'label--weight': '500',
          'text--color': 'var(--c--theme--colors--greyscale-600)',
          'text--size': 'var(--c--theme--font--sizes--s)',
          'text--weight': '400',
          'text--color-disabled': 'var(--c--theme--colors--greyscale-300)',
        },
        'forms-labelledbox': {
          'label-color--small': '#1E1E1E',
          'label-color--small--disabled': '#CECECE',
          'label-color--big': '#1E1E1E',
          'label-color--big--disabled': '#CECECE',
        },
        'forms-radio': {
          'border-color': 'var(--c--theme--colors--primary-800)',
          'background-color': 'var(--c--theme--colors--greyscale-000)',
          'accent-color': 'var(--c--theme--colors--primary-800)',
          'accent-color-disabled': 'var(--c--theme--colors--greyscale-300)',
        },
        'forms-switch': {
          'border--color-disabled': 'var(--c--theme--colors--greyscale-300)',
          'border--color': 'var(--c--theme--colors--primary-800)',
          'handle-background-color': 'white',
          'handle-background-color--disabled':
            'var(--c--theme--colors--greyscale-000)',
          'rail-background-color--disabled':
            'var(--c--theme--colors--greyscale-000)',
          'accent-color': 'var(--c--theme--colors--primary-800)',
        },
        'forms-textarea': {
          'label-color--focus': '#161616',
          'border-radius': '4px',
          'border-color': '#929292',
          'box-shadow--color--hover': '#929292',
          'box-shadow--color--focus': '#000091',
          'value-color': '#1E1E1E',
          'value-color--disabled': '#CECECE',
          'font-size': '14px',
        },
        'forms-input': {
          'label-color--focus': '#161616',
          'border-radius': '4px',
          'border-color': '#929292',
          'box-shadow--color--hover': '#929292',
          'box-shadow--color--focus': '#000091',
          'value-color': '#1E1E1E',
          'value-color--disabled': '#CECECE',
          'font-size': '14px',
        },
        'forms-select': {
          'label-color--focus': '#161616',
          'item-font-size': '14px',
          'border-radius': '4px',
          'border-radius-hover': '4px',
          'border-color': '#929292',
          'box-shadow--color--hover': '#929292',
          'box-shadow--color--focus': '#000091',
          'value-color': '#1E1E1E',
          'font-size': '14px',
        },
        'la-gauffre': { activated: true },
        'home-proconnect': { activated: true },
      },
    },
    dark: {
      theme: {
        colors: {
          'greyscale-100': '#182536',
          'greyscale-200': '#303C4B',
          'greyscale-300': '#555F6B',
          'greyscale-400': '#79818A',
          'greyscale-500': '#9EA3AA',
          'greyscale-600': '#C2C6CA',
          'greyscale-700': '#E7E8EA',
          'greyscale-800': '#F3F4F4',
          'greyscale-900': '#FAFAFB',
          'greyscale-000': '#0C1A2B',
          'primary-100': '#3B4C62',
          'primary-200': '#4D6481',
          'primary-300': '#6381A6',
          'primary-400': '#7FA5D5',
          'primary-500': '#8CB5EA',
          'primary-600': '#A3C4EE',
          'primary-700': '#C3D8F4',
          'primary-800': '#DDE9F8',
          'primary-900': '#F4F8FD',
          'success-100': '#EEF8D7',
          'success-200': '#D9F1B2',
          'success-300': '#BDE985',
          'success-400': '#A0E25D',
          'success-500': '#76D628',
          'success-600': '#5BB520',
          'success-700': '#43941A',
          'success-800': '#307414',
          'success-900': '#225D10',
          'warning-100': '#F7F3D5',
          'warning-200': '#F0E5AA',
          'warning-300': '#E8D680',
          'warning-400': '#E3C95F',
          'warning-500': '#D9B32B',
          'warning-600': '#BD9721',
          'warning-700': '#9D7B1C',
          'warning-800': '#7E6016',
          'warning-900': '#684D12',
          'danger-100': '#F8D0D0',
          'danger-200': '#F09898',
          'danger-300': '#F09898',
          'danger-400': '#ED8585',
          'danger-500': '#E96666',
          'danger-600': '#DD6666',
          'danger-700': '#C36666',
          'danger-800': '#AE6666',
          'danger-900': '#9D6666',
        },
      },
    },
  },
};
