# Generated by Django 5.1.5 on 2025-03-04 12:23
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_update_blank_title"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en-us", "English"),
                    ("fr-fr", "Français"),
                    ("de-de", "Deutsch"),
                ],
                default=None,
                help_text="The language in which the user wants to see the interface.",
                max_length=10,
                null=True,
                verbose_name="language",
            ),
        ),
    ]
