# Generated by Django 5.1.7 on 2025-03-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_remove_is_public_add_field_attachments_and_duplicated_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="has_deleted_children",
            field=models.BooleanField(default=False),
        ),
    ]
